sudo: required
services:
  - docker

before_install:
  - docker build -t my/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run my/react-test npm test -- --coverage

after_success:
  - docker build -t sageniuz/multi-client ./client
  - docker build -t sageniuz/multi-nginx ./nginx
  - docker build -t sageniuz/multi-server ./server
  - docker build -t sageniuz/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push sageniuz/multi-client
  - docker push sageniuz/multi-nginx
  - docker push sageniuz/multi-server
  - docker push sageniuz/multi-worker
